### ISSUE TITLE
Show number of hugepage total/free and size

### ISSUE THREAD

**Issue by John-Lin** [linkernetworks/vortex-portal#11]
![screen shot 2018-08-22 at 4 15 16 pm](https://user-images.githubusercontent.com/4214069/44451794-4bc5f500-a627-11e8-9b57-cefa6437ad43.png)
![screen shot 2018-08-22 at 4 21 31 pm](https://user-images.githubusercontent.com/4214069/44451844-757f1c00-a627-11e8-93ee-2209404f1ca3.png)

**Comment by John-Lin** [comment]
Prometheus check hugepage size variable `node_memory_Hugepagesize_bytes`

**Comment by WakeupTsai** [comment]
reference  #13

**Comment by John-Lin** [comment]
<img width="507" alt="screen shot 2018-08-28 at 1 11 42 am" src="https://user-images.githubusercontent.com/4214069/44674189-59341280-aa5f-11e8-80a6-5aaca2584721.png">
<img width="219" alt="screen shot 2018-08-28 at 1 12 00 am" src="https://user-images.githubusercontent.com/4214069/44674200-63561100-aa5f-11e8-841d-75336a49403b.png">


the first row showing the number of free/total hugepages
the second row showing the size of a hugepage

HugePages Free/Total: 512/1024
HugePages Size: 2048 KB

**Comment by John-Lin** [comment]
@WakeupTsai help wanted ~
