### ISSUE TITLE
[Bug] i8n Display error

### ISSUE THREAD

**Issue by John-Lin** [linkernetworks/vortex-portal#43]
![screen shot 2018-09-18 at 6 15 25 pm](https://user-images.githubusercontent.com/4214069/45681581-6fba1f00-bb70-11e8-9d24-9a37eeb1136e.png)

![screen shot 2018-09-18 at 6 15 38 pm](https://user-images.githubusercontent.com/4214069/45681583-6fba1f00-bb70-11e8-8341-0e232fe18c38.png)

@sufuf3 can you help this

**Comment by sufuf3** [comment]
OK
